language: smalltalk
sudo: false

smalltalk:
  - Pharo64-7.0
  - Pharo64-6.1
  - Pharo-6.1
  - Pharo-5.0
  - Squeak-trunk
  - Squeak-5.1
  - GemStone-2.4.8
  - GemStone-3.1.0.6
  - GemStone-3.2.16
  - GemStone-3.3.4


aliases:
  - &pharo4-has-latest-metacello
    smalltalk_config: .pharo4.ston

matrix:
  allow_failures:
    - smalltalk: Pharo-alpha
    - smalltalk: Squeak-trunk
      os: linux
 
  include:
    - smalltalk: Pharo-3.0
      <<: *pharo4-has-latest-metacello
    - smalltalk: Pharo-4.0
      <<: *pharo4-has-latest-metacello
    - smalltalk: Pharo64-7.0
      env: BUILD_NAME=Pharo64-7.0
    - smalltalk: Squeak-trunk
      env: BUILD_NAME=Squeak-trunk
