language: smalltalk
sudo: false

aliases:
  - &pharo4-has-latest-metacello
    smalltalk_config: .pharo4.ston

matrix:
  allow_failures:
    - smalltalk: Pharo64-9.0
    - smalltalk: Squeak-trunk
    - smalltalk: Squeak-5.1
 
  include:
    - smalltalk: Pharo64-9.0
      env: BUILD_NAME=Pharo64-9.0
    - smalltalk: Pharo64-8.0
      env: BUILD_NAME=Pharo64-8.0
    - smalltalk: Pharo64-7.0
      env: BUILD_NAME=Pharo64-7.0
    - smalltalk: Pharo64-6.1
      env: BUILD_NAME=Pharo64-6.1
    - smalltalk: Pharo-6.1
      env: BUILD_NAME=Pharo-6.1
    - smalltalk: Pharo-5.0
      env: BUILD_NAME=Pharo-5.0
    - smalltalk: Pharo-4.0
      <<: *pharo4-has-latest-metacello
      env: BUILD_NAME=Pharo-4.0
    - smalltalk: Squeak-trunk
      env: BUILD_NAME=Squeak-trunk
    - smalltalk: Squeak-5.2
      env: BUILD_NAME=Squeak-5.2
    - smalltalk: Squeak-5.1
      env: BUILD_NAME=Squeak-5.1
    - smalltalk: GemStone-3.5.0
      env: BUILD_NAME=GemStone-3.5.0
    - smalltalk: GemStone-3.4.3
      env: BUILD_NAME=GemStone-3.4.3
    - smalltalk: GemStone-3.3.9
      env: BUILD_NAME=GemStone-3.3.9
    - smalltalk: GemStone-3.2.17
      env: BUILD_NAME=GemStone-3.2.17
    - smalltalk: GemStone-3.1.0.6
      env: BUILD_NAME=GemStone-3.1.0.6
    - smalltalk: GemStone-2.4.8
      env: BUILD_NAME=GemStone-2.4.8
